version: 2.1
orbs:
  node: circleci/node@3.0.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: current
      - node/test:
          version: erbium
      - node/test:
          version: dubnium
