version: 2.1
orbs:
  node: circleci/node@3.0.0

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 14.x
      - node/test:
          version: 12.x
      - node/test:
          version: 10.x
