version: 2.1
orbs:
  node: circleci/node@4.4.0

jobs:
  test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
  test:
    jobs:
      - test
